//------------------------------------------------------------------------------
// <auto-generated>
//     Checked into source control for deterministic CLI builds.
//     Do not enable MSBuild StronglyTypedResource generation for Resources.resx
//     (see PilotBim.Analytics.csproj EmbeddedResource Generator=empty).
//     When adding keys: update Resources.resx and this file together.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PilotBim.Analytics.Properties
{
    using System;

    /// <summary>
    ///   Strongly typed resource class for UI string localization (default culture).
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources
    {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp =
                        new global::System.Resources.ResourceManager(
                            "PilotBim.Analytics.Properties.Resources",
                            typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture for all resource lookups.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        /// <summary>
        ///   Looks up a localized string similar to Сначала выполните сканирование.
        /// </summary>
        public static string Common_ScanRequiredFirst
        {
            get { return ResourceManager.GetString("Common_ScanRequiredFirst", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to Укажите заголовок.
        /// </summary>
        public static string Widget_EnterTitle
        {
            get { return ResourceManager.GetString("Widget_EnterTitle", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to Не удалось открыть каталог данных:\n
        /// </summary>
        public static string Catalog_OpenFailedPrefix
        {
            get { return ResourceManager.GetString("Catalog_OpenFailedPrefix", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to Не удалось открыть аналитику:\n
        /// </summary>
        public static string Analytics_OpenFailedPrefix
        {
            get { return ResourceManager.GetString("Analytics_OpenFailedPrefix", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to Укажите имя снимка.
        /// </summary>
        public static string Snapshot_EnterName
        {
            get { return ResourceManager.GetString("Snapshot_EnterName", resourceCulture); }
        }
    }
}
